version: '3.9'
services:
  snap-sort-db:
    image: postgres
    restart: unless-stopped
    container_name: snap-sort-db
    ports:
      - 5422:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
