import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/providers/providers';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { SideMenu } from '@/components/sidebar';
import { getServerSession } from '@/lib/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  console.log(session);
  return (
    <html lang='en'>
      <body>
        <Providers>
          <div className='min-h-screen grid  grid-rows-[auto,1fr,auto] '>
            <Header />
            <main className='flex gap-6 px-10'>
              <SideMenu />
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
